Bookstore: add reducers and actions
karanJ2212/bookstore_app pull request #2
Opened 2023-02-07 09:24 UTC by karanJ2212

In this milestone following features in redux folder are implemented

 Books actions and reducer  using the [ducks pattern]

Categories actions and reducer using the [ducks pattern]

Configured the Redux Store 

Imported the necessary methods from Redux Toolkit.
Combine both reducers into a root reducer by using configureStore function.

2023-02-07 11:05 UTC, emmiiorji requested changes
Hi @karanJ2212, 
# Status: Changes Required ♻️

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![BbcanBbcan3GIF](https://user-images.githubusercontent.com/20554583/217227622-1a58a919-6840-4da4-b298-9f2420f4a3d7.gif)

## Good Highlights✔️

- Linter checks are passing
- Good commit messages
- Proper use of GitHub flow


## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-07 11:05 UTC, emmiiorji commented on src/redux/books/books.js
> +const REMOVE_BOOK = 'REMOVE_BOOK';
You have done great at defining the action types. As specified in the requirements, kindly use the [duck's pattern](https://github.com/erikras/ducks-modular-redux). e.g `REMOVE_BOOK = bookstore/books/REMOVE_BOOK`

2023-02-07 11:05 UTC, emmiiorji commented on src/redux/categories/categories.js
> +const CHECK_STATUS = 'CHECK_STATUS';
As mentioned above, kindly ensure that all actions follow the [duck's pattern](https://github.com/erikras/ducks-modular-redux).

2023-02-07 11:09 UTC, emmiiorji commented
Hi @karanJ2212,

Kindly note that the approval on your dashboard was in error. Sorry about that as this will be reversed as soon as possible. 

Please, implement the changes and request a review again on your dashboard.

2023-02-07 18:09 UTC, MeqdamAlqudah reviewed
Hi @karanJ2212 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a pull request that was submitted for another project please create a new pull request and submit your project

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-02-08 08:50 UTC, enniopo commented
Hi @karanJ2212, you can now request a re-review for the "Bookstore: add reducers and actions" milestone. Your dashboard has been updated. Thank you, and apologies for the inconvenience.

2023-02-11 14:45 UTC, elisha2kyakpo1 approved these changes
Hi 👋 @karanJ2212, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

👍 You did a great job making the changes requested by the previous reviewer.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-11 14:45 UTC, elisha2kyakpo1 commented on src/redux/books/books.js
> +const REMOVE_BOOK = 'redux/books/books/REMOVE_BOOK';
- [ ] [OPTIONAL] Just writing `redux/books/ADD_BOOK` or `redux/books/REMOVE_BOOK` it's enough.

2023-02-11 15:20 UTC, merged